[pygbag]
title = Password Wizard
icon = favicon.png
cdn = https://pygame-web.github.io/cdn/0.9.3/

# Ignore unused directories containing MP3 files
ignore_dirs = pixel_defenders_project_assets/Audio,.git,.venv,__pycache__,build

# Ignore specific file types
ignore_files = *.mp3,*.aseprite,.DS_Store
